### ISSUE TITLE
missing script

### ISSUE THREAD

**Issue by jameshale** [gcanyon/navigator#10]
Double clicking on any item in Navigator's list brings up an error dialog about a missing "editBehaviorScript".
[Screen Recording 2018-10-23 at 10.54.17 am.mov.zip](https://github.com/gcanyon/navigator/files/2503782/Screen.Recording.2018-10-23.at.10.54.17.am.mov.zip)

I attached a screen recording.

**Comment by gcanyon** [comment]
Sorry I missed this until now. What version of Navigator do you have installed? This is an odd issue because Navigator has a special case for "Edit Behavior Script" and it shouldn't be looking for a command file to do that.

**Comment by jameshale** [comment]
Hi Geoff, Just tested with latest build. 
All ok.

(BTW my original issue was with the current Navigator and LC version at the time of posting, i.e. Oct 23 2018)

**Comment by gcanyon** [comment]
Glad to hear it!

gc
