### ISSUE TITLE
pop up menu from the target stack menu goes crazy on windows 10

### ISSUE THREAD

**Issue by soapdog** [gcanyon/navigator#11]
# Objective
Hold down the mouse button on the crosshair button that targets stacks so that it pops up a menu to list stacks list.

# Desired behavior
The menus pops up, I select _Stack list_ and the list appears.

# Actual outcome
The menu enters a popup loop, selecting an item causes it to close and then pop up again. I suspect it is some send in time bug loop or something similar.

The hole computer becomes unresponsive as the popup menu starts following the mouse and you can't really close apps.

**Comment by gcanyon** [comment]
This should be fixed by the most recent (6.6rc6) version of master.
