### ISSUE TITLE
Request: pDefaultFold = 0

### ISSUE THREAD

**Issue by madpink** [gcanyon/navigator#18]
I'd like option to have groups folded up on opening.

**Comment by gcanyon** [comment]
On the Actions menu, select Prefs...
In the Preferences dialog, in Display Options on the upper left, there is a Default Fold menu.
Select "1" on the Default Fold menu.
Click Set Prefs.

This should result in everything being folded when you browse a new container.

**Comment by madpink** [comment]
okay seriously, I thought I had tried that...

**Comment by gcanyon** [comment]
No problem.
