### ISSUE TITLE
FR: Preference option to ignore datagrids when folding groups

### ISSUE THREAD

**Issue by slylabs13** [gcanyon/navigator#26]
This is a feature request. I usually have groups within groups so I would like to set my fold level at 3, but then my Datagrids all unfold which defeats the whole purpose of folding for me, which is to minimize the lines in the list while still getting to the things I need. I almost NEVER need to unfold a datagrid.

**Comment by gcanyon** [comment]
7.2.1 includes a setting to fold data grids regardless of the default fold level. There is a checkbox in the preferences.
