### ISSUE TITLE
The MouseStack trick as a separate menu item

### ISSUE THREAD

**Issue by macMikey** [gcanyon/navigator#4]
The option-key/mousestack trick is handy and cool and deserves to be called out more or more visible, especially when working on the ide

**Comment by gcanyon** [comment]
Agreed, any suggestions?

**Comment by macMikey** [comment]
Any reason to not make it part of the main menu?

**Comment by gcanyon** [comment]
It would have to be in addition to the current entry on the stack menu,
since that's where it belongs -- you're choosing the stack to browse after
all.

**Comment by gcanyon** [comment]
I haven't made it an item in the main menu, but I have improved the functionality with the most recent update. I'm still thinking about the right way to further enhance/expand its presence in the Navigator UI.

**Comment by gcanyon** [comment]
The next (not released yet) update of Navigator now has a target menu. Click and it immediately goes to mouseStack mode. Click a bit longer, or just click and hold, and it pops up the stack menu.

**Comment by gcanyon** [comment]
Done!

**Comment by gcanyon** [comment]
This doesn't seem to want to close. In any case, it's done.
